language: ruby
cache: bundler
rvm:
  - 2.2.3
  - 2.3.0
gemfile:
  - gemfiles/activerecord_41.gemfile
  - gemfiles/activerecord_42.gemfile
  - gemfiles/activerecord_50.gemfile
  - gemfiles/mongoid_5.gemfile
  - gemfiles/sequel_4.gemfile
services:
  - mongodb
  - postgresql
before_install:
  - gem install bundler -v 1.10.6
before_script:
  - psql -c 'create database minimal_tags;' -U postgres
addons:
  code_climate:
    repo_token: 3c954617ba40beceb056cc73b82e00a6dc1fa2193cda386dc6c2128bdd61a804
  postgresql: "9.3"
