language: ruby
rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.3
services:
  - mongodb
  - postgresql
before_install:
  - gem install bundler -v 1.10.6
before_script:
  - psql -c 'create database minimal_tags;' -U postgres
addons:
  code_climate:
    repo_token: 3c954617ba40beceb056cc73b82e00a6dc1fa2193cda386dc6c2128bdd61a804
